### ISSUE TITLE
Omit the trailing space in self-closing XML tags

### ISSUE THREAD

**Issue by jeffhandley** [dotnet/api-docs-sync#73] opened 2021-04-18 06:19 UTC
Per https://github.com/dotnet/runtime/pull/48841/files#r585232027, I recommend we change the XML tag generation to omit the trailing space in self-closing tags. That would align with the behavior that VS provides when authoring XML doc comments, even though it's different from what we've done in dotnet-api-docs.

**Comment by gewarren** [comment] 2021-09-03 22:15
Same as #73?

**Comment by carlossanlop** [comment] 2022-08-17 20:24
Duplicate of #59

**Closed by carlossanlop** 2022-08-17 20:24 UTC
